# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=100)),
                ('vender_name', models.CharField(blank=True, default='', max_length=100)),
                ('mrp', models.CharField(blank=True, default='', max_length=100)),
                ('batch_num', models.CharField(blank=True, default='', max_length=100)),
                ('batch_date', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
