# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_inventoryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='is_approve',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='is_assistant',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='is_manager',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='batch_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
